// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LibraryTest1
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OmegaData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static OmegaData GetRootAsOmegaData(ByteBuffer _bb) { return GetRootAsOmegaData(_bb, new OmegaData()); }
  public static OmegaData GetRootAsOmegaData(ByteBuffer _bb, OmegaData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyOmegaData(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, OmegaDataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OmegaData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Time { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int Press { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Temp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public uint Vbat { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<LibraryTest1.OmegaData> CreateOmegaData(FlatBufferBuilder builder,
      uint time = 0,
      int press = 0,
      int temp = 0,
      uint vbat = 0) {
    builder.StartTable(4);
    OmegaData.AddVbat(builder, vbat);
    OmegaData.AddTemp(builder, temp);
    OmegaData.AddPress(builder, press);
    OmegaData.AddTime(builder, time);
    return OmegaData.EndOmegaData(builder);
  }

  public static void StartOmegaData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTime(FlatBufferBuilder builder, uint time) { builder.AddUint(0, time, 0); }
  public static void AddPress(FlatBufferBuilder builder, int press) { builder.AddInt(1, press, 0); }
  public static void AddTemp(FlatBufferBuilder builder, int temp) { builder.AddInt(2, temp, 0); }
  public static void AddVbat(FlatBufferBuilder builder, uint vbat) { builder.AddUint(3, vbat, 0); }
  public static Offset<LibraryTest1.OmegaData> EndOmegaData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<LibraryTest1.OmegaData>(o);
  }
  public static void FinishOmegaDataBuffer(FlatBufferBuilder builder, Offset<LibraryTest1.OmegaData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedOmegaDataBuffer(FlatBufferBuilder builder, Offset<LibraryTest1.OmegaData> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class OmegaDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Time*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Press*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Temp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Vbat*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
