// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LibraryTest
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OmegaDataList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static OmegaDataList GetRootAsOmegaDataList(ByteBuffer _bb) { return GetRootAsOmegaDataList(_bb, new OmegaDataList()); }
  public static OmegaDataList GetRootAsOmegaDataList(ByteBuffer _bb, OmegaDataList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyOmegaDataList(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, OmegaDataListVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OmegaDataList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public LibraryTest.OmegaDataV1_1? Items(int j) { int o = __p.__offset(4); return o != 0 ? (LibraryTest.OmegaDataV1_1?)(new LibraryTest.OmegaDataV1_1()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<LibraryTest.OmegaDataList> CreateOmegaDataList(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    OmegaDataList.AddItems(builder, itemsOffset);
    return OmegaDataList.EndOmegaDataList(builder);
  }

  public static void StartOmegaDataList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, Offset<LibraryTest.OmegaDataV1_1>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, Offset<LibraryTest.OmegaDataV1_1>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<LibraryTest.OmegaDataV1_1>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<LibraryTest.OmegaDataV1_1>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<LibraryTest.OmegaDataList> EndOmegaDataList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<LibraryTest.OmegaDataList>(o);
  }
  public static void FinishOmegaDataListBuffer(FlatBufferBuilder builder, Offset<LibraryTest.OmegaDataList> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedOmegaDataListBuffer(FlatBufferBuilder builder, Offset<LibraryTest.OmegaDataList> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class OmegaDataListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Items*/, LibraryTest.OmegaDataV1_1Verify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
