// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace LibraryTest
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct OmegaDataV1_1 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static OmegaDataV1_1 GetRootAsOmegaDataV1_1(ByteBuffer _bb) { return GetRootAsOmegaDataV1_1(_bb, new OmegaDataV1_1()); }
  public static OmegaDataV1_1 GetRootAsOmegaDataV1_1(ByteBuffer _bb, OmegaDataV1_1 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OmegaDataV1_1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Time { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int Press { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Temp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public uint Vbat { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<LibraryTest.OmegaDataV1_1> CreateOmegaDataV1_1(FlatBufferBuilder builder,
      uint time = 0,
      int press = 0,
      int temp = 0,
      uint vbat = 0) {
    builder.StartTable(4);
    OmegaDataV1_1.AddVbat(builder, vbat);
    OmegaDataV1_1.AddTemp(builder, temp);
    OmegaDataV1_1.AddPress(builder, press);
    OmegaDataV1_1.AddTime(builder, time);
    return OmegaDataV1_1.EndOmegaDataV1_1(builder);
  }

  public static void StartOmegaDataV1_1(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTime(FlatBufferBuilder builder, uint time) { builder.AddUint(0, time, 0); }
  public static void AddPress(FlatBufferBuilder builder, int press) { builder.AddInt(1, press, 0); }
  public static void AddTemp(FlatBufferBuilder builder, int temp) { builder.AddInt(2, temp, 0); }
  public static void AddVbat(FlatBufferBuilder builder, uint vbat) { builder.AddUint(3, vbat, 0); }
  public static Offset<LibraryTest.OmegaDataV1_1> EndOmegaDataV1_1(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<LibraryTest.OmegaDataV1_1>(o);
  }
}


static public class OmegaDataV1_1Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Time*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Press*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Temp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Vbat*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
